### ISSUE TITLE
Ongoing call not disconnecting when a callInvite is rejected during the call

### ISSUE THREAD

**Issue by nicolettemanas** [twilio/voice-callkit-quickstart-objc#7] opened 2017-03-06 09:43 UTC
Hi,

I'd like to confirm the following behavior I encountered using Twilio Voice Client 2.0.0-beta6.

I have an ongoing call between two users (caller and receiver), if a third user tries to call the receiver, the receiver rejects the call invite (as oppose to ignoring it shown in the quickstart app) while the ongoing call proceeds. When the **caller** ends the call, the call is not disconnect in the **receiver**. The method `callDidDisconnect:(TVOCall *)call` in the **receiver** is not executed. 

This also happens if the third user tries to call the **caller** (in the ongoing call) and rejects the invite, then the **receiver** ends the call. The method `callDidDisconnect:(TVOCall *)call` in the **caller** is not executed.

This behavior doesn't happen when the receiver chooses to ignore the call instead of rejecting it and calls are disconnected just fine. 

Is this a bug or are we advised to ignore the callInvites instead of rejecting it? We're currently rejecting it as we want the third user's call disconnected instead of having it ringing waiting for timeout.

Thanks!

**Comment by bchen-twilio** [comment] 2017-03-09 17:49
Hi @nicolettemanas 

Sorry for my late reply. This looks like a legit bug and we'll create a bug ticket for tracking this.
Though not documented, currently we would suggest apps to have only one active call and to not even surface a call-invite when it is already in a call, like the [example](https://github.com/twilio/voice-callkit-quickstart-objc/blob/master/ObjCVoiceCallKitQuickstart/ViewController.m#L150) in the `callInviteReceived:` callback method.

This doesn't happen in the `ignore` case since the app and SDK actually do nothing but literally ignore it. We'll take a look at why the `reject` is causing the missing of the subsequent call-did-disconnect callback.

Please stay tuned.
Cheers,
-bobie

**Comment by nicolettemanas** [comment] 2017-03-10 02:05
Hi @bchen-twilio 

Thank you for this. We will ignore the third call for now. 
Looking forward to the GA release!

**Comment by bchen-twilio** [comment] 2017-03-10 04:15
Thanks for understanding @nicolettemanas!

I did try to sort of break the one-active-call limitation and found the root cause of this issue. Although we'd still recommend SDK users to follow the limitation but I'll still include the fix into the next release iteration, just in case like this.
Could you shoot me a email (in the profile) so I can provide a patch for you to try?
Thanks.

-bobie

**Comment by bchen-twilio** [comment] 2017-03-18 17:57
Closing this issue since we've resolved in the latest beta release.
@nicolettemanas Please feel free to open new issues or reach out to us in the future. (hopefully you don't have to re-open this one :p)

**Closed by bchen-twilio** 2017-03-18 17:57 UTC
